# Configuration for mergeable - https://github.com/mergeability/mergeable

defaults:
  checks_failure_payload: &checks_failure_payload
    title: 'Mergeable Run have been Completed!'
    summary: |
      ### Status: {{toUpperCase validationStatus}}
          Here are some stats of the run:
          {{validationCount}} validations were ran.
          {{passCount}} PASSED
          {{failCount}} FAILED
    text: "{{#each validationSuites}}\n
          #### {{{statusIcon status}}} Validator: {{toUpperCase name}}\n
          {{#each validations }} * {{{statusIcon status}}} ***{{{ description }}}***\n
                  Input : {{{details.input}}}\n
                  Settings : {{{displaySettings details.settings}}}\n
                  {{/each}}\n
          {{/each}}"

version: 2
mergeable:
  - when: pull_request.opened
    name: "When pull_request.opened"
    validate: []
    pass:
      - do: assign
        assignees: [ '@author' ]
  - when: pull_request.*, pull_request_review.*
    name: 'Validate Pull Request Description'
    validate:
      - do: description
        no_empty:
          enabled: true
    fail:
      - do: checks
        status: 'failure'
        payload: *checks_failure_payload
      - do: comment
        payload:
          body: >
            Description is necessary and should not be empty. Kindly provide details with **what** was changed, **why** it was changed, and **how** it was changed.
  - when: pull_request.*, pull_request_review.*
    name: 'Validate Pull Request Size'
    validate:
      - do: size
        ignore:
          - '*.lock'
          - '*-lock.json'
        lines:
          max:
            count: 500
    fail:
      - do: checks
        status: 'failure'
        payload: *checks_failure_payload
      - do: comment
        payload:
          body: >
            Lines of code have too many changes. It should be under 500 lines of addtions and deletions.
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: dependent
        changed:
          file: 'pubspec.yaml'
          required: ['pubspec.lock']
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: title
        # Enforce semantic release convention.
        must_include:
          regex: ^(feat|docs|chore|fix|refactor|test|style|perf)(\(\w+\))?:.+$
          message: Semantic release conventions must be followed.
        # All todo check boxes must be checked.
      - do: description
        must_exclude:
          regex: \[ \]
          message: There are incomplete TODO task(s) unchecked.
      - do: approvals
        min:
          count: 1
        and:
          - required:
            reviewers: [ 'KalleHallden' ]
          - required:
            reviewers: [ 'tenshiAMD' ]
          - required:
            reviewers: [ 'jorre127' ]
          - required:
            reviewers: [ 'dinurymomshad' ]
