# Configuration for probot-stale - https://github.com/probot/stale

closeComment: false
daysUntilStale: 15
daysUntilClose: 7
staleLabel: stale
exemptLabels:
  - pinned
  - security

issues:
  markComment: >
    This issue has been automatically marked as stale because it has not had
    recent activity. It will be closed if no further activity occurs. 
    
    Thank you for your contributions.
  
pulls:
  markComment: >
      This pull request has been automatically marked as stale because it has not had
      recent activity. It will be closed if no further activity occurs. 
      
      Thank you for your contributions.
